services:
    bot_assist:
        env_file:
            - .env.${APP_ENV}
        build:
            args:
                user: mikhail
                uid: 1000
                APP_ENV: ${APP_ENV}
            context: ./
            dockerfile: docker-compose/dockerfiles/laravel.Dockerfile
            target: ${APP_ENV?}-target
        image: bot_assist-app
        depends_on:
            db:
                condition: service_started
            redis:
                condition: service_started
        ports:
            - "127.0.0.1:9000:9000"
            - "127.0.0.1:5173:5173"
        container_name: bot_assist-app
        restart: unless-stopped
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
        networks:
            - bot_assist
    db:
        image: mysql:5.7
        container_name: bot_assist-db
        restart: unless-stopped
        env_file:
            - .env.${APP_ENV}
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - bot_assist

    nginx:
        image: nginx:1.17-alpine
        container_name: bot_assist-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/app
            - ./docker-compose/nginx:/etc/nginx/configs
            - /etc/letsencrypt/:/etc/letsencrypt/
        networks:
            - bot_assist
        depends_on:
            bot_assist:
                condition: service_started
        command: >
            /bin/sh -c "
            ln -sf /etc/nginx/configs/bot_assist.${APP_ENV}.conf /etc/nginx/conf.d/default.conf;
            nginx -g 'daemon off;'
            "

    redis:
        image: redis:latest
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./docker-compose/redis/redis.${APP_ENV}.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "127.0.0.1:6379:6379"
        env_file:
            - .env.${APP_ENV}
        networks:
            - bot_assist
        container_name: bot_assist-redis

networks:
  bot_assist:
    driver: bridge
