<style>
    .bg-company {
        background-color: {{ $company->background_color }};
    }

    .text-company {
        color: {{ $company->text_color }};
    }

    .text-btn-bg-company {
        color: {{ $company->button_background_color }};
    }

    .border-company {
        border-color: {{ $company->border_color }};
    }

    .block-company {
        background-color: {{ $company->block_background_color }};
        color: {{ $company->text_color }};
    }

    .btn-shadow-company {
        box-shadow:
            inset 0 -200px 50px -130px {{ $company->button_background_color }},
            0px 0px 10px 0px rgba(0,0,0,0.3);
        color: {{ $company->button_text_color }};
    }

    .btn-shadow-company:focus {
        box-shadow:
            inset 0 -200px 50px -130px {{ $company->button_background_color }},
            0px 0px 10px 0px rgba(0,0,0,0.3),
            inset 0px 0px 10px 5px rgba(0,0,0,0.75);
        transition: .08s;
    }

    input:checked + .btn-shadow-company {
        box-shadow:
            inset 0 -200px 50px -130px {{ $company->button_background_color }},
            0px 0px 10px 0px rgba(0,0,0,0.3),
            inset 0px 0px 10px 5px rgba(0,0,0,0.75);
        transition: .08s;
    }

    .btn-company {
        background-color: {{ $company->button_background_color }};
        color: {{ $company->button_text_color }};
    }

    .main-block-company {
        background-color: {{ $company->main_background_color }};
        color: {{ $company->main_text_color }};
    }

    .additional-block-company {
        background-color: {{ $company->additional_background_color }};
        color: {{ $company->addtional_text_company }};
    }

    .box-shadow-basic {
        box-shadow: 0 0 30px 0 rgba(0,0,0,0.3);
    }

    .heartbeat {
        -webkit-animation: heartbeat 1.5s ease-in-out infinite both;
        animation: heartbeat 1.5s ease-in-out infinite both;
    }

    ::-webkit-scrollbar {
        display: none;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2024-5-26 23:44:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation heartbeat
     * ----------------------------------------
     */
    @-webkit-keyframes heartbeat {
        from {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-transform-origin: center center;
            transform-origin: center center;
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        10% {
            -webkit-transform: scale(0.91);
            transform: scale(0.91);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        17% {
            -webkit-transform: scale(0.98);
            transform: scale(0.98);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        33% {
            -webkit-transform: scale(0.87);
            transform: scale(0.87);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        45% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
    }
    @keyframes heartbeat {
        from {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-transform-origin: center center;
            transform-origin: center center;
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        10% {
            -webkit-transform: scale(0.91);
            transform: scale(0.91);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        17% {
            -webkit-transform: scale(0.98);
            transform: scale(0.98);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
        33% {
            -webkit-transform: scale(0.87);
            transform: scale(0.87);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
        45% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }
    }

</style>
